# Book settings

title: "NAPS Intermediate Physics"
author: Daniel Cartin
copyright: 2020-2021

#only_build_toc_files: true

# Execution settings

execute:
  execute_notebooks : false

# Book repository on GitHub

repository:
  url: https://github.com/dcartin/NAPS-Intermediate-Physics
  branch: master

# Add Google Analytics ID

html:
  google_analytics_id: G-SS32LXLKZD
